<<<<<<< HEAD
swagger: '2.0'
info:
  version: '1.0'
  title: "TrentinoEventi"
  description: Polls is a simple API allowing consumers to view polls and vote in them.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /questions:
    x-summary: Questions Collection
    get:
      summary: List All Questions
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
          examples:
            application/json:
              - question: Favourite programming language?
                published_at: '2015-08-05T08:40:51.620Z'
                choices:
                  - choice: Swift
                    votes: 2048
                  - choice: Python
                    votes: 1024
                  - choice: Objective-C
                    votes: 512
                  - choice: Ruby
                    votes: 256
    post:
      description: >-
        You may create your own question using this action. It takes a JSON
        object containing a question and a collection of answers in the
        form of choices.
      summary: Create a New Question
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/QuestionRequest'
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/Question'
          examples:
            application/json:
                question: Favourite programming language?
                published_at: '2015-08-05T08:40:51.620Z'
                choices:
                  - choice: Swift
                    votes: 0
                  - choice: Python
                    votes: 0
                  - choice: Objective-C
                    votes: 0
                  - choice: Ruby
                    votes: 0
definitions:
  Question:
    title: Question
    type: object
    properties:
      question:
        type: string
      published_at:
        type: string
      choices:
        type: array
        items:
          $ref: '#/definitions/Choice'
    required:
      - question
      - published_at
      - choices
  Choice:
    title: Choice
    type: object
    properties:
      votes:
        type: integer
        format: int32
      choice:
        type: string
    required:
      - votes
      - choice
  QuestionRequest:
    title: Question Request
    type: object
    properties:
      question:
        type: string
      choices:
        type: array
        items:
          type: string
    required:
      - question
      - choices
    example:
      question: Favourite programming language?
      choices:
        - Swift
        - Python
        - Objective-C
        - Ruby
=======
{"openapi":"3.0.0","info":{"title":"Trentino Eventi","description":"Applicazione che mostra eventi ed alloggi in Trentino","version":"1.0.0"},"servers":{"url":{"http":"//localhost:8080/","description":"Localhost"}},"paths":{"/api/v1/authentication/login":{"post":{"description":"Controlla se l utente esiste e in caso affermativo fa il login","summary":"Fa il login se l utente esiste","requestBody":{"content":{"application/json":{"schema":{"properties":{"email":{"type":"string","description":"Indirizzo email dell utente"},"password":{"type":"string","description":"Password dell utente"}}}}}},"responses":{"200":{"description":"Utente esiste e campi inseriti corretti","content":{"application/json":{"schema":{"properties":{"success":{"type":"boolean","description":"Vale true ed indica che non ci sono stati errori"}}}}}},"404":{"description":"Restituisce errori utente non trovato o password sbagliata!","content":{"application/json":{"schema":{"properties":{"success":{"type":"boolean","description":"Vale false ed indica che ci sono stati errori"},"message":{"type":"string","description":"Messaggio che contiene l'errore"}}}}}}}}},"/api/v1/authentication/subscribe":{"post":{"description":"Controlla se l utente esiste e in caso non affermativo lo iscrive","summary":"Fa la registazione se l utente non esiste","requestBody":{"content":{"application/json":{"schema":{"properties":{"name":{"type":"string","description":"Nome dell utente"},"surname":{"type":"string","description":"Cognome dell utente"},"birthdate":{"type":"string","description":"Data di nascita dell utente"},"userType":{"type":"string","description":"Tipo di utente"},"email":{"type":"string","description":"Indirizzo email dell utente"},"password":{"type":"string","description":"Password di utente"}}}}}},"responses":{"200":{"description":"Registrazione avvenuta correttamente","content":{"application/json":{"schema":{"properties":{"success":{"type":"boolean","description":"Vale true ed indica che non ci sono stati errori"}}}}}},"404":{"description":"Restituisce errore utente gia esistente!","content":{"application/json":{"schema":{"properties":{"success":{"type":"boolean","description":"Vale false ed indica che ci sono stati errori"},"message":{"type":"string","description":"Messaggio che contiene l'errore"}}}}}}}}},"/api/v1/authentication/checkIfLogged":{"get":{"description":"Controlla se l utente e gia loggato","summary":"Fa la registazione se l utente non esiste","responses":{"200":{"description":"Utente gia loggato","content":{"application/json":{"schema":{"properties":{"success":{"type":"boolean","description":"Vale true ed indica che non ci sono stati errori"},"name":{"type":"string","description":"Contiene il nome dell utente"},"message":{"type":"string","description":"Messaggio che contiene un messaggio di successo"}}}}}},"404":{"description":"Restituisce errori cookie non trovato e token non valido","content":{"application/json":{"schema":{"properties":{"success":{"type":"boolean","description":"Vale false ed indica che ci sono stati errori"},"message":{"type":"string","description":"Messaggio che contiene l'errore"}}}}}}}}}},"components":{},"tags":[]}
>>>>>>> login_samuele
